var GAME_LEVELS = [
  ["                                                                                        ",
   "                                                                                        ",
   "                                                                                        ",
   "                                              y                      y                  ",
   "                                              yy           y         yy                 ",
   "                                               yy         yy          y                 ",
   "                                                yy       yy          yy                 ",
   "                                                        yy           y                  ",
   "                                                                                        ",
   "                                                            y                           ",
   "  x                                        yy    y   yy    yy    y         y          x ",
   "  x                                             yy    y   yy     yy       yy          x ",
   "  x                                           yyy        yy       yy      y       f   x ",
   "  x                                                  f   y         yy            xxxxxx ",
   "  x      @                 *      o    xx      x    xxx    x  xxx   y  xx               ",
   "  x!!bbbbbbbbbbbbbbbb  xxxxxxxxxxxxxxxxxxx                                  xxxx        ",
   "  x!!bbbbbbbbbbbb      xxxxx            xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx          ",
   "  xbbbbbbbbbbbbb                         xxx!x!!x!!x!!x!!x!!x!!x!!x!!x!!xxxxx           ",
   "                                           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx              ",
   "                                                                                        ",
   "                                                                                        ",
   "  x o                                                                                 x ",
   "  xxxx                                                                                x ",
   "  x                 x                      x!x     x!x     x!x     x!x                x ",
   "  x   *     f      xxx       *            x!!!x f x!!!x f x!!!x f x!!!x    $          x ",
   "  xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb o xxxxxx!xxxxxxx!xxxxxxx!xxxxxxx!xxxxxxxxxxx  bbbbx ",
   "  xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxbbbbbbx ",
   "  xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbx ",
   "                                                                                        ",
   "                                                                                        "],
  ["bbbbbbbbbbbbbbwwwwwbbbbbbbbbbbbbbbbbwwwwwbbbbbbbbbbbbbbbbbbbbbbbbwwwwwbbbbbbbbbbbbbbbbbb",
   "               www                   www                          www                   ",
   "                w                     w                            w                    ",
   "                w                     w                            w                 o  ",
   "              ww ww                 ww ww                        ww ww            xxxxx ",
   "             w  |  w               w  |  w                      w  |  w                 ",
   "             w     w               w     w                      w     w                 ",
   "                                                                                        ",
   "                                                                           xxxx         ",
   "      *                            f                                                    ",
   "bbbbbbbbbbbb                      bbb       xx                                          ",
   "                                                                      bbbbbbb           ",
   "                            xx                     $                                    ",
   "                  f                           bbbbbbbbbbbb                              ",
   "                bbb                                                     *               ",
   "                                                                   xxxxxxxxxxxx         ",
   "    f *               xxx                                                               ",
   "xxxxxxxxxxxx                                                                            ",
   "             xxxxxx           f                                                         ",
   "                       bbbbbbbbbbbbbb                                                   ",
   "                                           f                                            ",
   "                                          bbb                                           ",
   "                                                                                        ",
   "                                             o                                          ",
   "                                            bbbbbbbbbb                                  ",
   "                                                                                        ",
   "                                                         bbb                            ",
   "                                                                  f                     ",
   "                                                               xxxxxxx                  ",
   "                                                                                 o      ",
   "                                                           f                bbbbbbbbbbbb",
   "                                                          xx                            ",
   "                      f                              f                                  ",
   "     @              xxxxx                    f      xx                                  ",
   "    xxx    wwww                 wwwww      wwwww                 wwwww        *       o ",
   "xxxxxxxxxxxxxww!!!!!!!!!!!!!!!!!wwxxw      wxxww                 wwxxxxxxxxxxxxxxxxxxxxx",
   "             ww!!!!!!!!!!!!!!!!!ww  w      w  ww!!!!!!!!!!!!!!!!!ww                     ",
   "             ww!!!!!!!!!!!!!!!!!ww  w      w  ww!!!!!!!!!!!!!!!!!ww                     ",
   "!!!!!!!!!!!!!!ww!!!!!!!!!!!!!!!ww!!!w  o   w!!!ww!!!!!!!!!!!!!!!ww!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!ww!!!!!!!!!!!!!ww!!!!wwwwwwww!!!!ww!!!!!!!!!!!!!ww!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!wwwwwwwwwwwww!!!!!!!!!!!!!!!!!!!!wwwwwwwwwwwww!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
   ["xxxxxxxxxxxxxxxxxx!xxxxxxxxxxxxxxxxxxxx!xxxxxxxxxxxxxxxxxxxx!xxxxxxxxxxxxxxxxxxxxxxxx!xx",
    "xxxxxxxxxxxxxxxxx!|!xxxxxxxxxxxxxxxxxx!|!xxxxxxxxxxxxxxxxxx!|!xxxxxxxxxxxxxxxxxxxxxx!|!x",
    "                                                                                        ",
    "                                                                                        ",
    "                                                                                        ",
    "                                                                                        ",
    "   @                        f                      f                      f             ",
    "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb       ",
    "                                                                                        ",
    "                                                                                        ",
    "                                                                                        ",
    "               *                    *             f                *                    ",
    "     wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
    "                                                                                        ",
    "                                                                                        ",
    "                                                                                        ",
    "                       *o                                       *                    o  ",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "                                                                                        ",
    "                                                                                        ",
    "                        *                   f                         *                 ",
    "     bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb!!|!!",
    "                                                                                        ",
    "                           f                                                            ",
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww        ",
    "                                                                                        ",
    "  o                         *                               *                           ",
    "xxxxxxxxxx       xxxxxxxxxxxxxxxxxx!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxx       xxxxxxx     ",
    "bbbbbbbbbbb       bbbbbbbbbbbbbbbbb!!!!!!!!!!!bbbbbbbbbbbbbbbbbbb       bbbbbbbbbbb     ",
    "wwwwwwwwwwww       wwwwwwwwwwwwwwwwwwwww!!wwwwwwwwwwwwwwwwww        wwwwwwwwwwwwwww     ",
    "xxxxxxxxxxxxx       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        xxxxxxxxxxxxxxxxxxx     ",
    "bbbbbbbbbbbbbbb       bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb         bbbbbbbbbbbbbbbbbb         ",
    "wwwwwwwwwwwwwwwwww       wwwwwwwwwwwwwwwwwwwwwwwwwwww       wwwwwwwwwwwwwwwwwww         ",
    "xxxxxxxxxxxxxxxxxxxx         xxxxxxxxxxxxxxxxxxxxxxxxxx         xxxxxxxxxxxxxxx      f  ",
    "bbbbbbbbbbbbbbbbbbbbb           bbbbbbbbbbbbbbbbbbbbbbbb           bbbbbbbbbbbb     bbbb",
    "wwwwwwwwwwwwwwwwwwwwwwww                  * o                   wwwwwwwwwwwwwww     wwww",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxx",
    "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb     bbbb",
    "wwwwwww!|!|!|!wwwwwwwwww!|!wwwwwwwwwwwwwwww!|!wwwwwwwwwwww!|!wwwwwwwwwwwwwwwwww     wwww",
    "                                                                                        ",
    "                                                                                        ",
    "                                                                                        ",
    "                                                                              f         ",
    "                                                                            bbbbb       ",
    "                                                                            wwwww       ",
    "                                                                          f xxxxx       ",
    "                                                                         bbbbb          ",
    "                                                                       wwwww            ",
    "                                                                   f xxxxxx             ",
    "                                     f                            bbbbb                 ",
    "                                                                  xxxxx                 ",
    "                                     *                                         *        ",
    "xxxx         xxxxxxxxxxx!!|!!xxxxxxxxxxxxxxxx!!|!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "bbbbbb       bbbbbbbbbbbb!!!bbbbbbbbbbbbbbbbbb!!!bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
    "wwwwwwww       wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
    "xxxxxxxx       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "bbbbbbbbbb       bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb bbb bbbbbbbbbbbbbbbb",
    "wwwwwwwwww       wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww       wwwwwwwwwwwwwww",
    "xxxxxxxxxxx      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         xxxxxxxxxxxxxx",
    "bbbbbbbbbbbb       bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb           bbbbbbbbbbbbb",
    "wwwwwwwwwwwww      wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww            wwwwwwwwwwwww",
    "xxxxxxxxxxxxxx                                                       f     xxxxxxxxxxxxx",
    "bbbbbbbbbbbbbbbb                                                  $       bbbbbbbbbbbbbb",
    "wwwwwwwwwwwwwwwwwwwwwwwww w w w w w w w w w w w w w wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
    ["                                                                                        ",
     "                                                                                        ",
     "                                                                                        ",
     "                                       @                                                ",
     "                                     xxxxx                                              ",
     "                                                                                        ",
     "                                                                                        ",
     "                                                                                        ",
     "                                                                                        ",
     "                                                                                        ",
     "                                                                                        ",
     "                                                                                        ",
     "                                                                                        ",
     "                                                                                        ",
     "                                                                                        ",
     "                                       $                                                ",
     "                                       f                                                ",
     "                                xxxxxxxxxxxxxxxxxx                                      ",
     "           y      yy  yyyyy  y   yy      y        yy   yy   yyy      y     yy           ",
     "            y    yy   y  yy  y   yy      y        yy   yy   y yy     y     yy           ",
     "             y  yy    y  yy  y   yy      y        yy   yy   y  yy    y     yy           ",
     "              yy      y  yy  y   yy      y   y    yy   yy   y   yy   y     yy           ",
     "              yy      y  yy  y   yy      y  y y   yy   yy   y    yy  y     yy           ",
     "              yy      y  yy  y   yy      y y   y  yy   yy   y     yy y     yy           ",
     "              yy      yyyyy  yyyyyy       y     yyy   yyyy  y      yyy                  ",
     "                                                                           yy           ",
     "                                                                           yy           "]

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
